### ISSUE TITLE
missing filter.h

### ISSUE THREAD

**Issue by owenduffy** [G8GYW/g8gyw.github.io#1]
Hi, I tried to build the code and it seems filter.h is missing?

Owen

**Comment by G8GYW** [comment]
Hi, you need to download the library from here:

https://www.megunolink.com/documentation/arduino-library/

The design has been cloned here:

https://m.aliexpress.com/item/1005003876018063.html

Mike

**Comment by owenduffy** [comment]
Thanks, I had guessed that MLP was a likely candidate. For PlatformIO, it builds with:

lib_deps = adafruit/Adafruit SSD1306@^2.5.7
           git@github.com:Megunolink/MLP.git

Yes, I purchased one of those Aliexpress implementations to try both your curve fitting technique and a cubic spline fit.

Thanks
Owen

**Comment by G8GYW** [comment]
Let me know how you get on!

Mike

**Comment by owenduffy** [comment]
Ok. A series of blog articles develops the fit alternatives starting at [Digital display for DIY 25W dummy load – part 1](https://owenduffy.net/blog/?p=26018).

I forked your repo and made some changes to build using PlatformIO.

I await the thing on a slow boat from China (currently 2-12weeks).

Owen

**Comment by G8GYW** [comment]
Thanks Owen.

Mike
