### ISSUE TITLE
Compatibility with Chinese SWR meter?

### ISSUE THREAD

**Issue by KDMcMullan** [G8GYW/g8gyw.github.io#3]
Hi.
A (Chinese ?) [SWR meter](https://www.aliexpress.com/item/1005007374325570.html) claims compatibility with "G8GYW" firmware.
Is that THIS firmware, please?
Thanks.

**Comment by G8GYW** [comment]
I believe so, but as I have no connection with the seller and haven't seen their meter I can't confirm it.

Owen Duffy has reviewed a Chinese version here: https://owenduffy.net/blog/?p=26973

**Comment by KDMcMullan** [comment]
Many thanks.
